<a href="https://colab.research.google.com/github/WatanabeGabriel/TFMC_test/blob/main/Exercicios_Numpy_II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Exercícios

1. Uma maneira de calcular o erro de um modelo preditivo é através do erro médio quadrático, que consiste em elevar ao quadrado a diferença de cada valor predito pelo valor real e depois tirar a média. Supondo que seu modelo fez 5 previsões y_pred = [1, 1, 1.1, 3.2, -0.5] e que os valores reais seriam: y_real = [0.3, 0.4, 1.1, 2.1, -0.9]. Calcule o erro médio quadrático.

$
e = \frac{1}{N}\sum(y_{real_i} - y_{pred_i} )^2
$


---




In [ ]:
y_real = np.array([0.3, 0.4, 1.1, 2.1, -0.9])
y_pred = np.array([1, 1, 1.1, 3.2, -0.5])

In [ ]:
e = 0
for i in (y_real - y_pred)**2:
  e += i
e = e / len(y_real)
print (e)

0.44400000000000006


In [ ]:
print(((y_real - y_pred)**2).mean())

0.44400000000000006



2. Um modelo calcula as probabilidades de três eventos acontecerem para uma determinada entrada. Suponha que esse modelo calculou as probabilidades abaixo para 5 entrada. Como você selecionaria qual a coluna que teve maior probabilidade em cada linha ?

```
[[0.2, 0.1, 0.7],
[0.3, 0.1, 0.6],
[0.5, 0.4, 0.1],
[0.3, 0.5, 0.2],
[0.1, 0.9, 0.0]]
```

---

In [ ]:
modelo = np.array([[0.2, 0.1, 0.7],[0.3, 0.1, 0.6],[0.5, 0.4, 0.1],[0.3, 0.5, 0.2],[0.1, 0.9, 0.0]])

In [ ]:
print(np.argmax(modelo, 1))

[2 2 0 1 1]


3. Crie uma matriz 5, 100 com números inteiros aleatórios entre 0 e 100. Subtraia a média de cada linha da matriz.

---



In [ ]:
matriz_aleatoria = np.random.randint(0,101,(5,10)) #### trocar de 10 p 100 ###
#print (matriz_aleatoria)
#len(matriz_aleatoria)

In [ ]:
matriz_aleatoria.shape

(5, 10)

In [ ]:
media = np.array(matriz_aleatoria.mean(1).reshape(len(matriz_aleatoria),1))
#print(media)

In [ ]:
matriz_2 = np.subtract(matriz_aleatoria, media)
print(matriz_2)

[[-35.6   1.4  28.4  11.4  40.4  32.4 -37.6  24.4 -27.6 -37.6]
 [-24.3 -23.3   5.7   7.7   4.7  43.7  48.7 -21.3 -46.3   4.7]
 [  5.6 -15.4  37.6  12.6 -21.4 -39.4 -10.4 -23.4  39.6  14.6]
 [-38.1  37.9  39.9 -21.1 -56.1 -42.1  -7.1  32.9  21.9  31.9]
 [ 56.8 -29.2  -0.2   6.8   3.8   5.8  -4.2 -27.2 -36.2  23.8]]


4. Usando a matriz do exercício anterior, divida cada linha de uma  pelo desvio padrão daquela linha.

---
# Nova seção

In [ ]:
dp_matriz_2 = np.reshape(np.std(matriz_2,1),(len(matriz_2),1))
#print(dp_matriz_2)

In [ ]:
matriz_div = np.divide(matriz_2, dp_matriz_2)
print(matriz_div)

[[-1.18192224  0.04648009  0.94288178  0.37848072  1.34128254  1.07568203
  -1.24832236  0.81008153 -0.91632173 -1.24832236]
 [-0.85129111 -0.81625855  0.19968557  0.26975068  0.16465301  1.5309227
   1.70608548 -0.74619344 -1.62200734  0.16465301]
 [ 0.22331503 -0.61411632  1.49940089  0.50245881 -0.85338242 -1.57118072
  -0.41472791 -0.93313779  1.57915626  0.58221418]
 [-1.07871431  1.07305177  1.12967719 -0.59739821 -1.58834311 -1.19196515
  -0.20102025  0.93148821  0.62004838  0.9031755 ]
 [ 2.17696437 -1.11914365 -0.00766537  0.26062249  0.14564198  0.22229566
  -0.16097272 -1.04248998 -1.38743152  0.91217873]]



5. Compare dois vetores para saber se todos elementos são iguais.

---



In [ ]:
sorteio = np.random.choice(len(matriz_div),2, replace=False)
#print(sorteio)
#print(matriz_div[sorteio[0]])
#print(matriz_div[sorteio[1]])
igualdade = np.equal(matriz_div[sorteio[0]], matriz_div[sorteio[1]])
print (igualdade)

[False False False False False False False False False False]


6. Crie uma matriz aleatória de tamanho 100x5. Divida cada coluna pelo maior valor daquela coluna

--- 


In [ ]:
matriz_aleatoria_2 = np.random.randint(100,size=(10,5)) #### trocar de 10 p 100 ###
#print (matriz_aleatoria_2.shape)

In [ ]:
maximos = np.array(matriz_aleatoria_2.max(1).reshape(len(matriz_aleatoria_2),1))
matriz_div_2 = np.divide(matriz_aleatoria_2 , maximos)
print(matriz_div_2)

[[1.         0.43283582 0.91044776 0.7761194  0.2238806 ]
 [0.70652174 0.02173913 0.14130435 1.         0.58695652]
 [0.92207792 0.74025974 1.         0.71428571 0.05194805]
 [0.83146067 0.05617978 0.08988764 1.         0.14606742]
 [0.39325843 1.         0.95505618 0.87640449 0.71910112]
 [0.0326087  0.2826087  0.73913043 0.29347826 1.        ]
 [0.         0.28888889 0.61111111 0.16666667 1.        ]
 [1.         0.98850575 0.56321839 0.47126437 0.11494253]
 [0.87640449 0.70786517 0.96629213 0.70786517 1.        ]
 [1.         0.70408163 0.51020408 0.46938776 0.05102041]]



7. Teste se uma coluna de uma matriz tem todos os valores constantes.

---


In [ ]:
#matriz_div_2[3] = [3,3,3,3,3] ### somete para testes
#print(matriz_div_2)

In [ ]:
sorteio = np.random.choice(len(matriz_div_2))
#sorteio = 3 ###somete para testes
const = True
med_2 = matriz_div_2[sorteio].mean()
for l in matriz_div_2[sorteio]:
  if l != med_2:
    const = False
    break
print (const)

False



8. Crie uma array com o códico abaixo. Depois escreva um código para selecionar aleatoriamente 20% das linhas e separe em uma outra matriz. Coloque os 80% das linhas restantes em uma segunda matriz.

```
mean = [0, 0]
cov = [[1, 2],
       [2, 5]]
X = rand.multivariate_normal(mean, cov, 100)
X.shape

```

---

In [8]:
mean = [0, 0]
cov = [[1, 2],
       [2, 5]]
X = np.random.multivariate_normal(mean, cov, 100)
X.shape

(100, 2)

In [9]:
 #X=np.random.randint(0,101,(10,2)) # foi usado para testes

In [10]:
np.random.shuffle(X)

In [11]:
X20, X80 = X[:int(len(X)*0.2)] , X[int(len(X)*0.2):]

In [12]:
#sorteio20 = np.random.choice(len(X),int(len(X)*0.2), replace=False) # tentando outra solução mas a acima foi melhor. Mantendo função somente p consulta
#sorteio20

In [13]:
#X20 = X[sorteio20]
#X20.shape

In [16]:
print("X shape: ", X.shape, " / X20 shape: ", X20.shape, " / X80 shape: ", X80.shape)

X shape:  (100, 2)  / X20 shape:  (20, 2)  / X80 shape:  (80, 2)



9. Suponha que existam valores faltantes em um array. Como você selecionaria apenas os elementos não faltantes? Como substituir os elementos faltantes pela média dos não faltantes? Considere o array abaixo:
```
np.array([1,2,3,np.nan,5,6,7,np.nan])
```


--- 


In [46]:
corrompido = np.array([1,2,3,np.nan,5,6,7,np.nan])

In [24]:
media_corrompido = np.nanmean(corrompido)

In [47]:
for i in range(len(corrompido)):
  if np.isnan(corrompido[i]) == True:
    print(i)
    corrompido[i] = media_corrompido

3
7



10. Como remover elementos duplicados de um array?
```
np.random.seed(100)
a = np.random.randint(0, 5, 10)
```
---




In [55]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)

In [56]:
a

array([0, 0, 3, 0, 2, 4, 2, 2, 2, 2])

In [59]:
np.unique(a)

array([0, 2, 3, 4])

11. Substitua todos os valores acima de 30 por 30 e os abaixo de 30 por 10.
```
np.random.seed(100)
a = np.random.uniform(1,50, 20)
```

---



In [60]:
np.random.seed(100)
b = np.random.uniform(1,50, 20)

In [61]:
b

array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  1.23122395,
        6.95688692, 33.86670515, 41.466785  ,  7.69862289, 29.17957314,
       44.67477576, 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       48.95256545, 40.77247431,  9.42510962, 40.99501269, 14.42961361])

In [62]:
b[b > 30] = 30
b[b < 30] = 10

In [63]:
print(b)

[10. 10. 10. 30. 10. 10. 30. 30. 10. 10. 30. 10. 10. 10. 10. 30. 30. 10.
 30. 10.]


12. Como contar o a quantidade de vezes que cada valor aparece em cada coluna de uma matriz de números inteiros.

--- 


In [65]:
matriz_12 = np.random.randint(0,101,(5,10))
matriz_12

array([[70,  3, 84, 79, 10, 87, 60,  3, 48, 52],
       [43, 36,  5, 71, 38, 86, 94, 98, 42, 84],
       [95, 76, 33, 58, 42, 22,  0, 55, 98, 19],
       [53, 68, 62, 50, 68, 35, 23,  9, 48, 21],
       [25, 54,  6, 37, 58, 39, 94, 51, 30, 66]])

In [69]:
matriz_12_valores, matriz_12_num_rep = np.unique(matriz_12, return_counts=True)[0] , np.unique(matriz_12, return_counts=True)[1]

In [76]:
for n in range(len(matriz_12_valores)):
  print("o valor ", matriz_12_valores[n], " se repete ", matriz_12_num_rep[n], [" vez", " vezes"][matriz_12_num_rep[n]>1])

o valor  0  se repete  1  vez
o valor  3  se repete  2  vezes
o valor  5  se repete  1  vez
o valor  6  se repete  1  vez
o valor  9  se repete  1  vez
o valor  10  se repete  1  vez
o valor  19  se repete  1  vez
o valor  21  se repete  1  vez
o valor  22  se repete  1  vez
o valor  23  se repete  1  vez
o valor  25  se repete  1  vez
o valor  30  se repete  1  vez
o valor  33  se repete  1  vez
o valor  35  se repete  1  vez
o valor  36  se repete  1  vez
o valor  37  se repete  1  vez
o valor  38  se repete  1  vez
o valor  39  se repete  1  vez
o valor  42  se repete  2  vezes
o valor  43  se repete  1  vez
o valor  48  se repete  2  vezes
o valor  50  se repete  1  vez
o valor  51  se repete  1  vez
o valor  52  se repete  1  vez
o valor  53  se repete  1  vez
o valor  54  se repete  1  vez
o valor  55  se repete  1  vez
o valor  58  se repete  2  vezes
o valor  60  se repete  1  vez
o valor  62  se repete  1  vez
o valor  66  se repete  1  vez
o valor  68  se repete  2  vezes
o v

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
  


---
---
# FIM
---
---